Locale_Text = {}






Locale_Text[10] = "Small Projectile Weapons"
Locale_Text[11] = "Development of a new type of small projectile weapons that can be deployed on tactical ships"
Locale_Text[12] = "Level 1 Small Projectile Weapon"
Locale_Text[13] = "Level 2 Small Projectile Weapon"
Locale_Text[14] = "Level 3 Small Projectile Weapon"
Locale_Text[15] = "Level 4 Small Projectile Weapon"
Locale_Text[16] = "Level 5 Small Projectile Weapon"
Locale_Text[17] = "Level 6 Small Projectile Weapon"
Locale_Text[18] = "Level 7 Small Projectile Weapon"
Locale_Text[19] = "Level 8 Small Projectile Weapon"
Locale_Text[20] = "Level 9 Small Projectile Weapon"
Locale_Text[21] = "Level 10 Small Projectile Weapon"

Locale_Text[50] = "Small Energy Weapons"
Locale_Text[51] = "Development of new small energy weapons that can be deployed on tactical ships"
Locale_Text[52] = "Level 1 Small Energy Weapon"
Locale_Text[53] = "Level 2 Small Energy Weapon"
Locale_Text[54] = "Level 3 Small Energy Weapon"
Locale_Text[55] = "Level 4 Small Energy Weapon"
Locale_Text[56] = "Level 5 Small Energy Weapon"
Locale_Text[57] = "Level 6 Small Energy Weapon"
Locale_Text[58] = "Level 7 Small Energy Weapon"
Locale_Text[59] = "Level 8 Small Energy Weapon"
Locale_Text[60] = "Level 9 Small Energy Weapon"
Locale_Text[61] = "Level 10 Small Energy Weapon"

Locale_Text[100] = "Small Guided Weapons"
Locale_Text[101] = "Development of new small guided weapons that can be deployed on tactical ships"
Locale_Text[102] = "Level 1 Small Guided Weapon"
Locale_Text[103] = "Level 2 Small Guided Weapon"
Locale_Text[104] = "Level 3 Small Guided Weapon"
Locale_Text[105] = "Level 4 Small Guided Weapon"
Locale_Text[106] = "Level 5 Small Guided Weapon"
Locale_Text[107] = "Level 6 Small Guided Weapon"
Locale_Text[108] = "Level 7 Small Guided Weapon"
Locale_Text[109] = "Level 8 Small Guided Weapon"
Locale_Text[110] = "Level 9 Small Guided Weapon"
Locale_Text[111] = "Level 10 Small Guided Weapon"


--------------------------------------------------------


Locale_Text[150] = "Medium Projectile Weapons"
Locale_Text[151] = "Development of a new medium-sized projectile weapon that can be deployed on tactical ships"
Locale_Text[152] = "Level 1 Medium Projectile Weapon"
Locale_Text[153] = "Level 2 Medium Projectile Weapon"
Locale_Text[154] = "Level 3 Medium Projectile Weapon"
Locale_Text[155] = "Level 4 Medium Projectile Weapon"
Locale_Text[156] = "Level 5 Medium Projectile Weapon"
Locale_Text[157] = "Level 6 Medium Projectile Weapon"
Locale_Text[158] = "Level 7 Medium Projectile Weapon"
Locale_Text[159] = "Level 8 Medium Projectile Weapon"
Locale_Text[160] = "Level 9 Medium Projectile Weapon"
Locale_Text[161] = "Level 10 Medium Projectile Weapon"


Locale_Text[200] = "Medium Energy Weapon"
Locale_Text[201] = "Development of new medium energy weapons that can be deployed on tactical ships"
Locale_Text[202] = "Level 1 Medium Energy Weapon"
Locale_Text[203] = "Level 2 Medium Energy Weapon"
Locale_Text[204] = "Level 3 Medium Energy Weapon"
Locale_Text[205] = "Level 4 Medium Energy Weapon"
Locale_Text[206] = "Level 5 Medium Energy Weapon"
Locale_Text[207] = "Level 6 Medium Energy Weapon"
Locale_Text[208] = "Level 7 Medium Energy Weapon"
Locale_Text[209] = "Level 8 Medium Energy Weapon"
Locale_Text[210] = "Level 9 Medium Energy Weapon"
Locale_Text[211] = "Level 10 Medium Energy Weapon"

Locale_Text[250] = "Medium Guided Weapons"
Locale_Text[251] = "Development of new medium guided weapons that can be deployed on tactical ships"
Locale_Text[252] = "Level 1 Medium Guided Weapon"
Locale_Text[253] = "Level 2 Medium Guided Weapon"
Locale_Text[254] = "Level 3 Medium Guided Weapon"
Locale_Text[255] = "Level 4 Medium Guided Weapon"
Locale_Text[256] = "Level 5 Medium Guided Weapon"
Locale_Text[257] = "Level 6 Medium Guided Weapon"
Locale_Text[258] = "Level 7 Medium Guided Weapon"
Locale_Text[259] = "Level 8 Medium Guided Weapon"
Locale_Text[260] = "Level 9 Medium Guided Weapon"
Locale_Text[261] = "Level 10 Medium Guided Weapon"

------------------------------------------------------------------------
Locale_Text[300] = "Large Projectile Weapons"
Locale_Text[301] = "Development of new large projectile weapons that can be deployed on tactical ships"
Locale_Text[302] = "Level 1 Large Projectile Weapon"
Locale_Text[303] = "Level 2 Large Projectile Weapon"
Locale_Text[304] = "Level 3 Large Projectile Weapon"
Locale_Text[305] = "Level 4 Large Projectile Weapon"
Locale_Text[306] = "Level 5 Large Projectile Weapon"
Locale_Text[307] = "Level 6 Large Projectile Weapon"
Locale_Text[308] = "Level 7 Large Projectile Weapon"
Locale_Text[309] = "Level 8 Large Projectile Weapon"
Locale_Text[310] = "Level 9 Large Projectile Weapon"
Locale_Text[311] = "Level 10 Large Projectile Weapon"


Locale_Text[350] = "Large Energy Weapons"
Locale_Text[351] = "Development of new large energy weapons that can be deployed on tactical ships"
Locale_Text[352] = "Level 1 Large Energy Weapon"
Locale_Text[353] = "Level 2 Large Energy Weapon"
Locale_Text[354] = "Level 3 Large Energy Weapon"
Locale_Text[355] = "Level 4 Large Energy Weapon"
Locale_Text[356] = "Level 5 Large Energy Weapon"
Locale_Text[357] = "Level 6 Large Energy Weapon"
Locale_Text[358] = "Level 7 Large Energy Weapon"
Locale_Text[359] = "Level 8 Large Energy Weapon"
Locale_Text[360] = "Level 9 Large Energy Weapon"
Locale_Text[361] = "Level 10 Large Energy Weapon"

Locale_Text[400] = "Large Guided Weapons"
Locale_Text[401] = "Development of new large guided weapons that can be deployed on tactical ships"
Locale_Text[402] = "Level 1 Large Guided Weapon"
Locale_Text[403] = "Level 2 Large Guided Weapon"
Locale_Text[404] = "Level 3 Large Guided Weapon"
Locale_Text[405] = "Level 4 Large Guided Weapon"
Locale_Text[406] = "Level 5 Large Guided Weapon"
Locale_Text[407] = "Level 6 Large Guided Weapon"
Locale_Text[408] = "Level 7 Large Guided Weapon"
Locale_Text[409] = "Level 8 Large Guided Weapon"
Locale_Text[410] = "Level 9 Large Guided Weapon"
Locale_Text[411] = "Level 10 Large Guided Weapon"
---------------------------------------------------------------------
Locale_Text[500] = "Hull Technology"
Locale_Text[501] = "Development of a new type of hull for tactical ships"
Locale_Text[502] = "Level 1 Hull Technology"
Locale_Text[503] = "Level 2 Hull Technology"
Locale_Text[504] = "Level 3 Hull Technology"
Locale_Text[505] = "Level 4 Hull Technology"
Locale_Text[506] = "Level 5 Hull Technology"
Locale_Text[507] = "Level 6 Hull Technology"
Locale_Text[508] = "Level 7 Hull Technology"
Locale_Text[509] = "Level 8 Hull Technology"
Locale_Text[510] = "Level 9 Hull Technology"
Locale_Text[511] = "Level 10 Hull Technology"

Locale_Text[550] = "Shield Technology"
Locale_Text[551] = "Development of new shields for use by tactical ships"
Locale_Text[552] = "Level 1 Shield Technology"
Locale_Text[553] = "Level 2 Shield Technology"
Locale_Text[554] = "Level 3 Shield Technology"
Locale_Text[555] = "Level 4 Shield Technology"
Locale_Text[556] = "Level 5 Shield Technology"
Locale_Text[557] = "Level 6 Shield Technology"
Locale_Text[558] = "Level 7 Shield Technology"
Locale_Text[559] = "Level 8 Shield Technology"
Locale_Text[560] = "Level 9 Shield Technology"
Locale_Text[561] = "Level 10 Shield Technology"

Locale_Text[600] = "Armor Technology"
Locale_Text[601] = "Development of new armor modules for use by tactical ships"
Locale_Text[602] = "Level 1 Armor Technology"
Locale_Text[603] = "Level 2 Armor Technology"
Locale_Text[604] = "Level 3 Armor Technology"
Locale_Text[605] = "Level 4 Armor Technology"
Locale_Text[606] = "Level 5 Armor Technology"
Locale_Text[607] = "Level 6 Armor Technology"
Locale_Text[608] = "Level 7 Armor Technology"
Locale_Text[609] = "Level 8 Armor Technology"
Locale_Text[610] = "Level 9 Armor Technology"
Locale_Text[611] = "Level 10 Armor Technology"

Locale_Text[650] = "Fire Control Technology"
Locale_Text[651] = "Develop new fire control modules for use on tactical ships, increasing firepower by 50% per stage"
Locale_Text[652] = "Level 1 Fire Control Technology"
Locale_Text[653] = "Level 2 Fire Control Technology"
Locale_Text[654] = "Level 3 Fire Control Technology"
Locale_Text[655] = "Level 4 Fire Control Technology"
Locale_Text[656] = "Level 5 Fire Control Technology"
Locale_Text[657] = "Level 6 Fire Control Technology"
Locale_Text[658] = "Level 7 Fire Control Technology"
Locale_Text[659] = "Level 8 Fire Control Technology"
Locale_Text[660] = "Level 9 Fire Control Technology"
Locale_Text[661] = "Level 10 Fire Control Technology"

Locale_Text[700] = "Repair Technology"
Locale_Text[701] = "Development of new repair systems for use on tactical ships"
Locale_Text[702] = "Level 1 Repair Technology"
Locale_Text[703] = "Level 2 Repair Technology"
Locale_Text[704] = "Level 3 Repair Technology"
Locale_Text[705] = "Level 4 Repair Technology"
Locale_Text[706] = "Level 5 Repair Technology"
Locale_Text[707] = "Level 6 Repair Technology"
Locale_Text[708] = "Level 7 Repair Technology"
Locale_Text[709] = "Level 8 Repair Technology"
Locale_Text[710] = "Level 9 Repair Technology"
Locale_Text[711] = "Level 10 Repair Technology"

Locale_Text[750] = "Detection Technology"
Locale_Text[751] = "Develop new detection systems for use on tactical ships to increase their detection range"
Locale_Text[752] = "Level 1 Detection Technology"
Locale_Text[753] = "Level 2 Detection Technology"
Locale_Text[754] = "Level 3 Detection Technology"
Locale_Text[755] = "Level 4 Detection Technology"
Locale_Text[756] = "Level 5 Detection Technology"

Locale_Text[800] = "Power Technology"
Locale_Text[801] = "Development of new power systems for tactical ships, note: heavy tactical ships and above are unable to use the power module"
Locale_Text[802] = "Level 1 Power Technology"
Locale_Text[803] = "Level 2 Power Technology"
Locale_Text[804] = "Level 3 Power Technology"
Locale_Text[805] = "Level 4 Power Technology"
Locale_Text[806] = "Level 5 Power Technology"


Locale_Text[850] = "Drone Technology"
Locale_Text[851] = "New drones developed for use on tactical ships"
Locale_Text[852] = "Level 1 Drone Technology"
Locale_Text[853] = "Level 2 Drone Technology"
Locale_Text[854] = "Level 3 Drone Technology"
Locale_Text[855] = "Level 4 Drone Technology"
Locale_Text[856] = "Level 5 Drone Technology"
Locale_Text[857] = "Level 6 Drone Technology"
Locale_Text[858] = "Level 7 Drone Technology"
Locale_Text[859] = "Level 8 Drone Technology"
Locale_Text[860] = "Level 9 Drone Technology"
Locale_Text[861] = "Level 10 Drone Technology"

Locale_Text[900] = "Drone Fire Control Technology"
Locale_Text[901] = "Strengthens the weapons of all drones, increasing firepower"
Locale_Text[902] = "Level 1 Drone Fire Control Technology"
Locale_Text[903] = "Level 2 Drone Fire Control Technology"
Locale_Text[904] = "Level 3 Drone Fire Control Technology"
Locale_Text[905] = "Level 4 Drone Fire Control Technology"
Locale_Text[906] = "Level 5 Drone Fire Control Technology"
Locale_Text[907] = "Level 6 Drone Fire Control Technology"
Locale_Text[908] = "Level 7 Drone Fire Control Technology"
Locale_Text[909] = "Level 8 Drone Fire Control Technology"
Locale_Text[910] = "Level 9 Drone Fire Control Technology"
Locale_Text[911] = "Level 10 Drone Fire Control Technology"

Locale_Text[950] = "Drone Armor Technology"
Locale_Text[951] = "Strengthens the armor of all drones, enhancing defense"
Locale_Text[952] = "Level 1 Drone Armor Technology"
Locale_Text[953] = "Level 2 Drone Armor Technology"
Locale_Text[954] = "Level 3 Drone Armor Technology"
Locale_Text[955] = "Level 4 Drone Armor Technology"
Locale_Text[956] = "Level 5 Drone Armor Technology"
Locale_Text[957] = "Level 6 Drone Armor Technology"
Locale_Text[958] = "Level 7 Drone Armor Technology"
Locale_Text[959] = "Level 8 Drone Armor Technology"
Locale_Text[960] = "Level 9 Drone Armor Technology"
Locale_Text[961] = "Level 10 Drone Armor Technology"

Locale_Text[1001] = "Bounty System"
Locale_Text[1002] = "Increase the bounty multiplier, doubling the RU reward for each ship destroyed"
Locale_Text[1003] = "Bounty x1.5"
Locale_Text[1004] = "Bounty x2"
Locale_Text[1005] = "Bounty x2.2"
Locale_Text[1006] = "Bounty x2.4"
Locale_Text[1007] = "Bounty x2.6"
Locale_Text[1008] = "Bounty x2.8"
Locale_Text[1009] = "Bounty x3"
Locale_Text[1010] = "Bounty x3.2"
Locale_Text[1011] = "Bounty x3.4"
Locale_Text[1012] = "Bounty x3.5"


--------------------------------------------------------------------------------
Locale_Text[1300] = "Flagship Projectile Weapons"
Locale_Text[1301] = "Development of new flagship-class projectile weapons that can be deployed on tactical ships"
Locale_Text[1302] = "Level 1 Flagship Projectile Weapon"
Locale_Text[1303] = "Level 2 Flagship Projectile Weapon"
Locale_Text[1304] = "Level 3 Flagship Projectile Weapon"
Locale_Text[1305] = "Level 4 Flagship Projectile Weapon"
Locale_Text[1306] = "Level 5 Flagship Projectile Weapon"
Locale_Text[1307] = "Level 6 Flagship Projectile Weapon"
Locale_Text[1308] = "Level 7 Flagship Projectile Weapon"
Locale_Text[1309] = "Level 8 Flagship Projectile Weapon"
Locale_Text[1310] = "Level 9 Flagship Projectile Weapon"
Locale_Text[1311] = "Level 10 Flagship Projectile Weapon"


Locale_Text[1350] = "Flagship Energy Weapons"
Locale_Text[1351] = "Development of new flagship-class energy weapons that can be deployed on tactical ships"
Locale_Text[1352] = "Level 1 Flagship Energy Weapon"
Locale_Text[1353] = "Level 2 Flagship Energy Weapon"
Locale_Text[1354] = "Level 3 Flagship Energy Weapon"
Locale_Text[1355] = "Level 4 Flagship Energy Weapon"
Locale_Text[1356] = "Level 5 Flagship Energy Weapon"
Locale_Text[1357] = "Level 6 Flagship Energy Weapon"
Locale_Text[1358] = "Level 7 Flagship Energy Weapon"
Locale_Text[1359] = "Level 8 Flagship Energy Weapon"
Locale_Text[1360] = "Level 9 Flagship Energy Weapon"
Locale_Text[1361] = "Level 10 Flagship Energy Weapon"

Locale_Text[1400] = "Flagship Guided Weapons"
Locale_Text[1401] = "Development of new flagship-class guided weapons that can be deployed on tactical ships"
Locale_Text[1402] = "Level 1 Flagship Guided Weapon"
Locale_Text[1403] = "Level 2 Flagship Guided Weapon"
Locale_Text[1404] = "Level 3 Flagship Guided Weapon"
Locale_Text[1405] = "Level 4 Flagship Guided Weapon"
Locale_Text[1406] = "Level 5 Flagship Guided Weapon"
Locale_Text[1407] = "Level 6 Flagship Guided Weapon"
Locale_Text[1408] = "Level 7 Flagship Guided Weapon"
Locale_Text[1409] = "Level 8 Flagship Guided Weapon"
Locale_Text[1410] = "Level 9 Flagship Guided Weapon"
Locale_Text[1411] = "Level 10 Flagship Guided Weapon"

Locale_Text[1500] = "Floating Gun Fire Control Technology"
Locale_Text[1501] = "Strengthens the weapons of all floating guns, enhancing firepower"
Locale_Text[1502] = "Level 1 Floating Gun Fire Control Technology"
Locale_Text[1503] = "Level 2 Floating Gun Fire Control Technology"
Locale_Text[1504] = "Level 3 Floating Gun Fire Control Technology"
Locale_Text[1505] = "Level 4 Floating Gun Fire Control Technology"
Locale_Text[1506] = "Level 5 Floating Gun Fire Control Technology"
Locale_Text[1507] = "Level 6 Floating Gun Fire Control Technology"
Locale_Text[1508] = "Level 7 Floating Gun Fire Control Technology"
Locale_Text[1509] = "Level 8 Floating Gun Fire Control Technology"
Locale_Text[1510] = "Level 9 Floating Gun Fire Control Technology"
Locale_Text[1511] = "Level 10 Floating Gun Fire Control Technology"

Locale_Text[1550] = "Floating Gun Armor Technology"
Locale_Text[1551] = "Strengthens the armor of all floating guns, enhancing defense"
Locale_Text[1552] = "Level 1 Floating Gun Armor Technology"
Locale_Text[1553] = "Level 2 Floating Gun Armor Technology"
Locale_Text[1554] = "Level 3 Floating Gun Armor Technology"
Locale_Text[1555] = "Level 4 Floating Gun Armor Technology"
Locale_Text[1556] = "Level 5 Floating Gun Armor Technology"
Locale_Text[1557] = "Level 6 Floating Gun Armor Technology"
Locale_Text[1558] = "Level 7 Floating Gun Armor Technology"
Locale_Text[1559] = "Level 8 Floating Gun Armor Technology"
Locale_Text[1560] = "Level 9 Floating Gun Armor Technology"
Locale_Text[1561] = "Level 10 Floating Gun Armor Technology"

Locale_Text[1650] = "Heavy Artillery Weapon System Technology"
Locale_Text[1651] = "More advanced heavy artillery weapon systems can be developed"
Locale_Text[1652] = "Level 1 Heavy Artillery Weapon System Technology"
Locale_Text[1653] = "Level 2 Heavy Artillery Weapon System Technology"
Locale_Text[1654] = "Level 3 Heavy Artillery Weapon System Technology"
Locale_Text[1655] = "Level 4 Heavy Artillery Weapon System Technology"
Locale_Text[1656] = "Level 5 Heavy Artillery Weapon System Technology"
Locale_Text[1657] = "Level 6 Heavy Artillery Weapon System Technology"
Locale_Text[1658] = "Level 7 Heavy Artillery Weapon System Technology"
Locale_Text[1659] = "Level 8 Heavy Artillery Weapon System Technology"
Locale_Text[1660] = "Level 9 Heavy Artillery Weapon System Technology"
Locale_Text[1661] = "Level 10 Heavy Artillery Weapon System Technology"


Locale_Text[1750] = "Rapid-Fire Gun Weapon System Technology"
Locale_Text[1751] = "More advanced rapid-fire gun weapon systems could be developed"
Locale_Text[1752] = "Level 1 Rapid-Fire Weapon System Technology"
Locale_Text[1753] = "Level 2 Rapid-Fire Weapon System Technology"
Locale_Text[1754] = "Level 3 Rapid-Fire Weapon System Technology"
Locale_Text[1755] = "Level 4 Rapid-Fire Weapon System Technology"
Locale_Text[1756] = "Level 5 Rapid-Fire Weapon System Technology"
Locale_Text[1757] = "Level 6 Rapid-Firem Weapon System Technology"
Locale_Text[1758] = "Level 7 Rapid-Fire Weapon System Technology"
Locale_Text[1759] = "Level 8 Rapid-Fire Weapon System Technology"
Locale_Text[1760] = "Level 9 Rapid-Fire Weapon System Technology"
Locale_Text[1761] = "Level 10 Rapid-Fire Weapon System Technology"

Locale_Text[1850] = "Beam Weapon System Technology"
Locale_Text[1851] = "More advanced beam weapon systems can be developed"
Locale_Text[1852] = "Level 1 Beam Weapon System Technology"
Locale_Text[1853] = "Level 2 Beam Weapon System Technology"
Locale_Text[1854] = "Level 3 Beam Weapon System Technology"
Locale_Text[1855] = "Level 4 Beam Weapon System Technology"
Locale_Text[1856] = "Level 5 Beam Weapon System Technology"
Locale_Text[1857] = "Level 6 Beam Weapon System Technology"
Locale_Text[1858] = "Level 7 Beam Weapon System Technology"
Locale_Text[1859] = "Level 8 Beam Weapon System Technology"
Locale_Text[1860] = "Level 9 Beam Weapon System Technology"
Locale_Text[1861] = "Level 10 Beam Weapon System Technology"

Locale_Text[1950] = "Energy Bomb Weapon System Technology"
Locale_Text[1951] = "More advanced energy bomb weapon systems can be developed"
Locale_Text[1952] = "Level 1 Energy Bomb Weapon System Technology"
Locale_Text[1953] = "Level 2 Energy Bomb Weapon System Technology"
Locale_Text[1954] = "Level 3 Energy Bomb Weapon System Technology"
Locale_Text[1955] = "Level 4 Energy Bomb Weapon System Technology"
Locale_Text[1956] = "Level 5 Energy Bomb Weapon System Technology"
Locale_Text[1957] = "Level 6 Energy Bomb Weapon System Technology"
Locale_Text[1958] = "Level 7 Energy Bomb Weapon System Technology"
Locale_Text[1959] = "Level 8 Energy Bomb Weapon System Technology"
Locale_Text[1960] = "Level 9 Energy Bomb Weapon System Technology"
Locale_Text[1961] = "Level 10 Energy Bomb Weapon System Technology"

Locale_Text[2050] = "Guided Weapon System Technology"
Locale_Text[2051] = "More advanced guided weapon systems can be developed"
Locale_Text[2052] = "Level 1 Guided Weapon System Technology"
Locale_Text[2053] = "Level 2 Guided Weapon System Technology"
Locale_Text[2054] = "Level 3 Guided Weapon System Technology"
Locale_Text[2055] = "Level 4 Guided Weapon System Technology"
Locale_Text[2056] = "Level 5 Guided Weapon System Technology"
Locale_Text[2057] = "Level 6 Guided Weapon System Technology"
Locale_Text[2058] = "Level 7 Guided Weapon System Technology"
Locale_Text[2059] = "Level 8 Guided Weapon System Technology"
Locale_Text[2060] = "Level 9 Guided Weapon System Technology"
Locale_Text[2061] = "Level 10 Guided Weapon System Technology"