Locale_Text = {}



Locale_Text[100] = "Increased resource synthesis yield for resource refining ships"
Locale_Text[101] = "Increase resource refining ship resource synthesis yield"
Locale_Text[102] = "Increase resource refining ship resource synthesis yield by 1"
Locale_Text[103] = "Increase resource refining ship resource synthesis yield by 2"
Locale_Text[104] = "Resource refining ship resource synthesis production increased by 3"
Locale_Text[105] = "Resource refining ship resource synthesis yield increased by 4"
Locale_Text[106] = "Resource refining ship resource synthesis yield increased by 5"
Locale_Text[107] = "Resource refining ship resource synthesis yield increased by 6"
Locale_Text[108] = "Resource refining ship resource synthesis yield increased by 7"
Locale_Text[109] = "Resource refining ship resource synthesis yield increased by 8"
Locale_Text[110] = "Resource refining ship resource synthesis yield increased by 9"
Locale_Text[111] = "Resource refining ship resource synthesis yield increased by 10"

Locale_Text[150] = "Torpedo destroyer technology"
Locale_Text[151] = "Build torpedo destroyers with efficient anti-primary and flagship"
Locale_Text[152] = "Torpedo destroyer racks"
Locale_Text[153] = "Upgrade torpedo destroyer armor"
Locale_Text[154] = "Torpedo destroyer armor upgrade 1"
Locale_Text[155] = "Torpedo destroyer armor upgrade 2"
Locale_Text[156] = "Upgrade torpedo destroyer firepower"
Locale_Text[157] = "Torpedo destroyer firepower upgrade 1"
Locale_Text[158] = "Torpedo destroyer firepower upgrade 2"

Locale_Text[200] = "Heavy Cruiser Technology"
Locale_Text[201] = "A smaller version of the battlecruiser, equipped with a large number of anti-aircraft weapons"
Locale_Text[202] = "Heavy cruiser frame"

Locale_Text[210] = "Anti-aircraft destroyer armor upgrade"
Locale_Text[215] = "Air defense destroyer speed upgrade"

Locale_Text[220] = "Pulse turret armor"
Locale_Text[221] = "Upgrade armor of pulse turrets"
Locale_Text[222] = "Pulse turret armor upgrade 1"
Locale_Text[223] = "Upgrade pulse turret armor 2"


Locale_Text[230] = "Sayuk"
Locale_Text[231] = "Summon Sajuk, who is guarding Hiigara Prime, to the battle"
Locale_Text[232] = "Sajuk summon"



Locale_Text[250] = "Dreadnought technology"
Locale_Text[251] = "Build defensive dreadnoughts with great defensive capabilities, shorter development time but longer construction time"
Locale_Text[252] = "Defensive dreadnought technology"
Locale_Text[253] = "Speed up repair of defense dreadnoughts"
Locale_Text[254] = "Dreadnought self-repair system"
Locale_Text[255] = "Upgrade dreadnought armor"
Locale_Text[256] = "Dreadnought armor upgrades"

Locale_Text[260] = "Battleship technology"
Locale_Text[261] = "Build torpedo battleships with powerful torpedo attacks"
Locale_Text[262] = "Battleship racks"
Locale_Text[263] = "Upgrade the armor of battleships"
Locale_Text[264] = "Battleship armor upgrade 1"
Locale_Text[265] = "Battleship armor upgrade 2"
Locale_Text[266] = "Battleship armor upgrade 3"
Locale_Text[267] = "Upgrade battleship firepower"
Locale_Text[268] = "Upgrade battleship firepower"

Locale_Text[270] = "Cruiser technology"
Locale_Text[271] = "Upgrade armor of heavy cruisers"
Locale_Text[272] = "Upgrade heavy cruiser armor"
Locale_Text[273] = "Upgrade heavy cruiser speed"
Locale_Text[274] = "Upgrade heavy cruiser speed"

Locale_Text[280] = "Super fighter tech"
Locale_Text[281] = "An advanced fighter obtained from ancestral technology, with perfect offensive and defensive capabilities"
Locale_Text[282] = "Stagecoach fighter"


Locale_Text[290] = "Support battleship technology"
Locale_Text[291] = "Build Bishop-class battleships with excellent performance"
Locale_Text[292] = "Support battleship racks"
Locale_Text[293] = "Upgrade support battleship armor"
Locale_Text[294] = "Support battleship armor upgrade 1"
Locale_Text[295] = "Support battleship armor upgrade 2"
Locale_Text[296] = "Upgrade support battleship firepower"
Locale_Text[297] = "Support battleship firepower upgrade 1"
Locale_Text[298] = "Support battleship firepower upgrade 2"



Locale_Text[300] = "Key of Sayuk technology"
Locale_Text[301] = "Build an ancestor battleship with a powerful ion cannon"
Locale_Text[302] = "Key of Sayuk"
Locale_Text[303] = "Upgrade the armor of the Key of Sayuk"
Locale_Text[304] = "Sayuk's Key armor upgrade 1"
Locale_Text[305] = "Upgrade Sayuk's Key's firepower"
Locale_Text[306] = "Key of Sayuk firepower upgrade 1"
Locale_Text[307] = "Key of Sayuk fire upgrade 2"


Locale_Text[500] = "Heavy Defense Platform Technology"
Locale_Text[501] = "A heavy torpedo defense platform that can withstand massive fleet attacks"
Locale_Text[502] = "heavy defense platform rack"
Locale_Text[503] = "Upgrade the armor of heavy defense platforms"
Locale_Text[504] = "Heavy defense platform armor upgrade 1"
Locale_Text[505] = "Upgrade heavy defense platform armor 2"
Locale_Text[506] = "Heavy defense platform armor upgrade 3"
Locale_Text[507] = "Upgrade firepower of heavy defense platforms"
Locale_Text[508] = "Upgrade heavy defense platform firepower"

Locale_Text[600] = "Armored assault ship technology"
Locale_Text[601] = "Build armored assault ships with heavy armor"
Locale_Text[602] = "Armored assault ship frame"
Locale_Text[603] = "Upgrade armor of armored assault ships"
Locale_Text[604] = "Armor assault ship armor upgrade 1"
Locale_Text[605] = "Armor Assault Ship Armor Upgrade 2"
Locale_Text[606] = "Upgrade armor assault ship's firepower"
Locale_Text[607] = "Armored assault ship firepower upgrade 1"
Locale_Text[608] = "Upgrade firepower of armored assault ships 2"

Locale_Text[700] = "Scepter-class cruiser technology"
Locale_Text[701] = "Build scepter class cruiser with heavy armor"
Locale_Text[702] = "Scepter-class cruiser frame"
Locale_Text[703] = "Upgrade the armor of the Scepter-class cruiser"
Locale_Text[704] = "Scepter-class cruiser armor upgrade 1"
Locale_Text[705] = "Scepter-class cruiser armor upgrade 2"
Locale_Text[706] = "Upgrade firepower of Scepter-class cruiser"
Locale_Text[707] = "Scepter-class cruiser firepower upgrade 1"
Locale_Text[708] = "Scepter-class cruiser firepower upgrade 2"

Locale_Text[800] = "Cremour-class battleship technology"
Locale_Text[801] = "Build Cremor-class battleships with powerful electromagnetic railguns"
Locale_Text[802] = "Cremor-class battleship frame"
Locale_Text[803] = "Upgrade the armor of Cremor-class battleships"
Locale_Text[804] = "Cremor-class battleship armor upgrade 1"
Locale_Text[805] = "Kremor-class battleship armor upgrade 2"
Locale_Text[806] = "Upgrade firepower of Cremor-class battleships"
Locale_Text[807] = "Cremor-class battleship firepower upgrade 1"
Locale_Text[808] = "Cremor-class battleship firepower upgrade 2"



Locale_Text[900] = "Atalanta-class destroyer technology"
Locale_Text[901] = "Build Atalanta-class destroyers with powerful electromagnetic railguns"
Locale_Text[902] = "Atalanta destroyer frame"
Locale_Text[903] = "Upgrade the armor of the Atalanta-class destroyer"
Locale_Text[904] = "Atalanta class destroyer armor upgrade 1"
Locale_Text[905] = "Atalanta destroyer armor upgrade 2"
Locale_Text[906] = "Upgrade firepower of Atalanta-class destroyers"
Locale_Text[907] = "Atalanta-class destroyer firepower upgrade 1"
Locale_Text[908] = "Atalanta-class destroyer firepower upgrade 2"


Locale_Text[1050] = "Godfrey Pulse Boat Technology"
Locale_Text[1051] = "Build efficient anti-primary and flagship Shepard-class pulse boats"
Locale_Text[1052] = "Shepard-class pulse boat frame"
Locale_Text[1053] = "Upgrade the armor of the Shepard pulse boat"
Locale_Text[1054] = "Shepard pulse boat armor upgrade 1"
Locale_Text[1055] = "Shepard pulse boat armor upgrade 2"
Locale_Text[1056] = "Upgrade the firepower of the Shepard pulse boat"
Locale_Text[1057] = "Shepard pulse boat firepower upgrade 1"
Locale_Text[1058] = "Shepard-class pulse boat firepower upgrade 2"


Locale_Text[1150] = "Shepard-class pulse boat technology"
Locale_Text[1151] = "Build efficient anti-primary and flagship Shepard-class pulse boats"
Locale_Text[1152] = "Shepard-class pulse boat frame"
Locale_Text[1153] = "Upgrade the armor of the Shepard pulse boat"
Locale_Text[1154] = "Shepard pulse boat armor upgrade 1"
Locale_Text[1155] = "Shepard pulse boat armor upgrade 2"
Locale_Text[1156] = "Upgrade the firepower of the Shepard pulse boat"
Locale_Text[1157] = "Shepard pulse boat firepower upgrade 1"
Locale_Text[1158] = "Firepower upgrade 2 for the Godfrey pulse boat"


Locale_Text[1160] = "Khaos class frigate hull"
Locale_Text[1161] = "A general purpose frigate hull with several modifications"
Locale_Text[1162] = "Caius-class frigate technology"

Locale_Text[1200] = "Scafa Ru destroyer hull"
Locale_Text[1201] = "A general purpose destroyer hull with many modifications"
Locale_Text[1202] = "Scafaru destroyer technology"


Locale_Text[1250] = "Starhunter technology"
Locale_Text[1251] = "Air fighter developed by Sylphon and Caius"
Locale_Text[1252] = "Starhunter frame"
Locale_Text[1253] = "Upgrade the Star Hunter's armor"
Locale_Text[1254] = "Starhunter armor upgrade 1"
Locale_Text[1255] = "Starhunter armor upgrade 2"
Locale_Text[1256] = "Upgrade Starhunter firepower"
Locale_Text[1257] = "Starhunter firepower upgrade 1"
Locale_Text[1258] = "Starhunter firepower upgrade 2"



Locale_Text[1300] = "Imperial reinforcements"
Locale_Text[1301] = "Summon Empress-class megaships from the Fai'ri Empire for reinforcements"
Locale_Text[1302] = "Diplomatic aid agreement"



Locale_Text[1450] = "Advanced Dreadnought Technology"
Locale_Text[1451] = "To build an Ariel-class dreadnought with strong defense capabilities, the research and development time is relatively short, but the construction time is relatively long"
Locale_Text[1452] = "Ariel Class Broken Dreadnought Technology"
Locale_Text[1453] = "Speed up the repair speed of Arithier-class broken dreadnoughts"
Locale_Text[1454] = "Dreadnought self-healing system"
Locale_Text[1455] = "Upgrade the armor of the dreadnought"
Locale_Text[1456] = "Dreadnought Armor Upgrade"
------------??--------------------------------------------------------
Locale_Text[6510] = "Survival Mothership Upgrade"
Locale_Text[6511] = "Upgrade the armor of the Survival Mothership"

Locale_Text[6520] = "Survival Mothership Armor Upgrade 1"
Locale_Text[6521] = "Survival Mothership Armor Upgrade 2"
Locale_Text[6522] = "Survival Mothership Armor Upgrade 3"
Locale_Text[6523] = "Survival Mothership Armor Upgrade 4"
Locale_Text[6524] = "Survival Mothership Armor Upgrade 5"
Locale_Text[6525] = "Survival Mothership Armor Upgrade 6"
Locale_Text[6526] = "Survival Mothership Armor Upgrade 7"
Locale_Text[6527] = "Survival Mothership Armor Upgrade 8"
Locale_Text[6528] = "Survival Mothership Armor Upgrade 9"
Locale_Text[6529] = "Survival Mothership Armor Upgrade 10"
Locale_Text[6610] = "Survival Mothership Upgrade"
Locale_Text[6611] = "Increase the speed of the Survival Mothership"

Locale_Text[6620] = "Survival Mothership Speed Upgrade 1"
Locale_Text[6621] = "Survival Mothership Speed Upgrade 2"
Locale_Text[6622] = "Survival Mothership Speed Upgrade 3"
Locale_Text[6623] = "Survival Mothership Speed Upgrade 4"
Locale_Text[6624] = "Survival Mothership Speed Upgrade 5"
Locale_Text[6625] = "Survival Mothership Speed Upgrade 6"
Locale_Text[6626] = "Survival Mothership Speed Upgrade 7"
Locale_Text[6627] = "Survival Mothership Speed Upgrade 8"
Locale_Text[6628] = "Survival Mothership Speed Upgrade 9"
Locale_Text[6629] = "Survival Mothership Speed Upgrade 10"
Locale_Text[6710] = "Survival Mothership Upgrade"
Locale_Text[6711] = "Increase the summoning speed of the Survival Mothership"

Locale_Text[6720] = "Survival Mothership Summoning Speed Upgrade 1"
Locale_Text[6721] = "Survival Mothership Summoning Speed Upgrade 2"
Locale_Text[6722] = "Survival Mothership Summoning Speed Upgrade 3"
Locale_Text[6723] = "Survival Mothership Summoning Speed Upgrade 4"
Locale_Text[6724] = "Survival Mothership Summoning Speed Upgrade 5"
Locale_Text[6725] = "Survival Mothership Summoning Speed Upgrade 6"
Locale_Text[6726] = "Survival Mothership Summoning Speed Upgrade 7"
Locale_Text[6727] = "Survival Mothership Summoning Speed Upgrade 8"
Locale_Text[6728] = "Survival Mothership Summoning Speed Upgrade 9"
Locale_Text[6729] = "Survival Mothership Summoning Speed Upgrade 10"

Locale_Text[6810] = "Survival Mothership Upgrade"
Locale_Text[6811] = "Increase the repair speed of the Survival Mothership"

Locale_Text[6820] = "Survival Mothership Repair Speed Upgrade 1"
Locale_Text[6821] = "Survival Mothership Repair Speed Upgrade 2"
Locale_Text[6822] = "Survival Mothership Repair Speed Upgrade 3"
Locale_Text[6823] = "Survival Mothership Repair Speed Upgrade 4"
Locale_Text[6824] = "Survival Mothership Repair Speed Upgrade 5"
Locale_Text[6825] = "Survival Mothership Repair Speed Upgrade 6"
Locale_Text[6826] = "Survival Mothership Repair Speed Upgrade 7"
Locale_Text[6827] = "Survival Mothership Repair Speed Upgrade 8"
Locale_Text[6828] = "Survival Mothership Repair Speed Upgrade 9"
Locale_Text[6829] = "Survival Mothership Repair Speed Upgrade 10"